[server]
address = "127.0.0.1:25565"
playerName = "33ss"
online = false
reconnect = true

[private]
name = "private.toml"


[nbt]
# anchor means the first block in your schematic file (nbt)
anchor = "-64,-60,-65"

# the nbt file you want to build
name = "kafka/kafka_swim_suit_1_6.nbt"

tempblock = "minecraft:cobblestone"


[other]
home = "tp @p -70 -60 -80"


[algorithm]
# available algorithm: slice_dfs
method = "slice_dfs"

# retry is the number of times we retry an action
retry = 12


[move]
use_flash = true


# The fields below represent each block and the position of the chest they are stored in.
# Recycle is the chest you can put everything in it.
# You can use recycle chest as item classifier's source chest.
[[chests]]
name = "recycle"
coordinate = ["-63,-50,-91", "-63,-50,-92", "-63,-50,-93", "-63,-50,-94", "-63,-50,-95", "-63,-50,-96"]
[[chests]]
name = "minecraft:cooked_beef"
coordinate = ["-68,-60,-92"]
[[chests]]
name = "minecraft:white_wool"
coordinate = ["-61,-59,-93", "-61,-58,-93"]
[[chests]]
name = "minecraft:light_gray_wool"
coordinate = ["-60,-59,-93", "-60,-58,-93"]
[[chests]]
name = "minecraft:gray_wool"
coordinate = ["-59,-59,-93", "-59,-58,-93"]
[[chests]]
name = "minecraft:black_wool"
coordinate = ["-58,-59,-93", "-58,-58,-93"]
[[chests]]
name = "minecraft:red_wool"
coordinate = ["-57,-59,-93", "-57,-58,-93"]
[[chests]]
name = "minecraft:orange_wool"
coordinate = ["-56,-59,-93", "-56,-58,-93"]
[[chests]]
name = "minecraft:yellow_wool"
coordinate = ["-55,-59,-93", "-55,-58,-93"]
[[chests]]
name = "minecraft:lime_wool"
coordinate = ["-54,-59,-93", "-54,-58,-93"]
[[chests]]
name = "minecraft:green_wool"
coordinate = ["-53,-59,-93", "-53,-58,-93"]
[[chests]]
name = "minecraft:light_blue_wool"
coordinate = ["-52,-59,-93", "-52,-58,-93"]
[[chests]]
name = "minecraft:cyan_wool"
coordinate = ["-51,-59,-93", "-51,-58,-93"]
[[chests]]
name = "minecraft:blue_wool"
coordinate = ["-50,-59,-93", "-50,-58,-93"]
[[chests]]
name = "minecraft:purple_wool"
coordinate = ["-49,-59,-93", "-49,-58,-93"]
[[chests]]
name = "minecraft:magenta_wool"
coordinate = ["-48,-59,-93", "-48,-58,-93"]
[[chests]]
name = "minecraft:pink_wool"
coordinate = ["-47,-59,-93", "-47,-58,-93"]
[[chests]]
name = "minecraft:brown_wool"
coordinate = ["-46,-59,-93", "-46,-58,-93"]
[[chests]]
name = "minecraft:white_terracotta"
coordinate = ["-61,-59,-80", "-61,-58,-80"]
[[chests]]
name = "minecraft:light_gray_terracotta"
coordinate = ["-60,-59,-80", "-60,-58,-80"]
[[chests]]
name = "minecraft:gray_terracotta"
coordinate = ["-59,-59,-80", "-59,-58,-80"]
[[chests]]
name = "minecraft:black_terracotta"
coordinate = ["-58,-59,-80", "-58,-58,-80"]
[[chests]]
name = "minecraft:red_terracotta"
coordinate = ["-57,-59,-80", "-57,-58,-80"]
[[chests]]
name = "minecraft:orange_terracotta"
coordinate = ["-56,-59,-80", "-56,-58,-80"]
[[chests]]
name = "minecraft:yellow_terracotta"
coordinate = ["-55,-59,-80", "-55,-58,-80"]
[[chests]]
name = "minecraft:lime_terracotta"
coordinate = ["-54,-59,-80", "-54,-58,-80"]
[[chests]]
name = "minecraft:green_terracotta"
coordinate = ["-53,-59,-80", "-53,-58,-80"]
[[chests]]
name = "minecraft:light_blue_terracotta"
coordinate = ["-52,-59,-80", "-52,-58,-80"]
[[chests]]
name = "minecraft:cyan_terracotta"
coordinate = ["-51,-59,-80", "-51,-58,-80"]
[[chests]]
name = "minecraft:blue_terracotta"
coordinate = ["-50,-59,-80", "-50,-58,-80"]
[[chests]]
name = "minecraft:purple_terracotta"
coordinate = ["-49,-59,-80", "-49,-58,-80"]
[[chests]]
name = "minecraft:magenta_terracotta"
coordinate = ["-48,-59,-80", "-48,-58,-80"]
[[chests]]
name = "minecraft:pink_terracotta"
coordinate = ["-47,-59,-80", "-47,-58,-80"]
[[chests]]
name = "minecraft:brown_terracotta"
coordinate = ["-46,-59,-80", "-46,-58,-80"]
[[chests]]
name = "minecraft:grass_block"
coordinate = ["-61,-54,-93", "-61,-53,-93"]
[[chests]]
name = "minecraft:cobblestone"
coordinate = ["-60,-54,-93", "-60,-53,-93", "-53,-54,-80", "-53,-53,-80"]
[[chests]]
name = "minecraft:dirt"
coordinate = ["-59,-54,-93", "-59,-53,-93"]
[[chests]]
name = "minecraft:deepslate"
coordinate = ["-58,-54,-93", "-58,-53,-93"]
[[chests]]
name = "minecraft:gold_block"
coordinate = ["-57,-54,-93", "-57,-53,-93"]
[[chests]]
name = "minecraft:iron_block"
coordinate = ["-56,-54,-93", "-56,-53,-93"]
[[chests]]
name = "minecraft:raw_iron_block"
coordinate = ["-55,-54,-93", "-55,-53,-93"]
[[chests]]
name = "minecraft:lapis_block"
coordinate = ["-54,-54,-93", "-54,-53,-93"]
[[chests]]
name = "minecraft:emerald_block"
coordinate = ["-53,-54,-93", "-53,-53,-93"]
[[chests]]
name = "minecraft:redstone_block"
coordinate = ["-52,-54,-93", "-52,-53,-93"]
[[chests]]
name = "minecraft:prismarine_bricks"
coordinate = ["-51,-54,-93", "-51,-53,-93"]
[[chests]]
name = "minecraft:netherrack"
coordinate = ["-50,-54,-93", "-50,-53,-93"]
[[chests]]
name = "minecraft:warped_nylium"
coordinate = ["-49,-54,-93", "-49,-53,-93"]
[[chests]]
name = "minecraft:crimson_nylium"
coordinate = ["-48,-54,-93", "-48,-53,-93"]
[[chests]]
name = "minecraft:clay"
coordinate = ["-47,-54,-93", "-47,-53,-93"]
[[chests]]
name = "minecraft:glass"
coordinate = ["-46,-54,-93", "-46,-53,-93"]
[[chests]]
name = "minecraft:oak_planks"
coordinate = ["-61,-54,-80", "-61,-53,-80"]
[[chests]]
name = "minecraft:spruce_planks"
coordinate = ["-60,-54,-80", "-60,-53,-80"]
[[chests]]
name = "minecraft:birch_planks"
coordinate = ["-59,-54,-80", "-59,-53,-80"]
[[chests]]
name = "minecraft:jungle_planks"
coordinate = ["-58,-54,-80", "-58,-53,-80"]
[[chests]]
name = "minecraft:crimson_planks"
coordinate = ["-57,-54,-80", "-57,-53,-80"]
[[chests]]
name = "minecraft:warped_planks"
coordinate = ["-56,-54,-80", "-56,-53,-80"]
[[chests]]
name = "minecraft:crimson_hyphae"
coordinate = ["-55,-54,-80", "-55,-53,-80"]
[[chests]]
name = "minecraft:warped_hyphae"
coordinate = ["-54,-54,-80", "-54,-53,-80"]
[[chests]]
name = "minecraft:diorite"
coordinate = ["-52,-54,-80", "-52,-53,-80"]
[[chests]]
name = "minecraft:oak_leaves"
coordinate = ["-51,-54,-80", "-51,-53,-80"]
[[chests]]
name = "minecraft:packed_ice"
coordinate = ["-50,-54,-80", "-50,-53,-80"]
[[chests]]
name = "minecraft:mushroom_stem"
coordinate = ["-49,-54,-80", "-49,-53,-80"]
[[chests]]
name = "minecraft:verdant_froglight"
coordinate = ["-48,-54,-80", "-48,-53,-80"]
[[chests]]
name = "minecraft:nether_wart_block"
coordinate = ["-47,-54,-80", "-47,-53,-80"]