include(ExternalProject)

set(BOTCRAFT_GIT_REPOSITORY "https://github.com/adepierre/Botcraft")
set(BOTCRAFT_GIT_BRANCH "master")

set(BOTCRAFT_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/dependency/botcraft")
set(BOTCRAFT_BUILD_PATH "${BOTCRAFT_ROOT}/build")
set(BOTCRAFT_INSTALL_PATH "${BOTCRAFT_ROOT}/output")
set(BOTCRAFT_HEADER_PATH "${BOTCRAFT_INSTALL_PATH}/include")
set(BOTCRAFT_LIB_PATH "${BOTCRAFT_INSTALL_PATH}/lib")
set(BOTCRAFT_BINARY_PATH "${BOTCRAFT_INSTALL_PATH}/bin")

if(NOT EXISTS "${BOTCRAFT_ROOT}/.git")
  message(STATUS "Update submodule")
  execute_process(COMMAND ${GIT_EXECUTABLE} submodule update --init --recursive
                          WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
                          RESULT_VARIABLE GIT_SUBMOD_RESULT)
endif()

ExternalProject_Add(Botcraft
  SOURCE_DIR ${BOTCRAFT_ROOT}
  BINARY_DIR ${BOTCRAFT_BUILD_PATH}
  PREFIX ${BOTCRAFT_ROOT}
  STEP_TARGETS install
  EXCLUDE_FROM_ALL TRUE
  CMAKE_GENERATOR ${CMAKE_GENERATOR}
  CONFIGURE_COMMAND ${CMAKE_COMMAND} -S ${BOTCRAFT_ROOT} -B ${BOTCRAFT_BUILD_PATH} -G ${CMAKE_GENERATOR} -DBOTCRAFT_USE_OPENGL_GUI=ON -DBOTCRAFT_USE_IMGUI=ON -DCMAKE_CXX_FLAGS="-Wa,-mbig-obj" -DBOTCRAFT_GAME_VERSION=${MC_VERSION}
  BUILD_COMMAND ${CMAKE_COMMAND} --build ${BOTCRAFT_BUILD_PATH}
  INSTALL_COMMAND ${CMAKE_COMMAND} --install ${BOTCRAFT_BUILD_PATH} --prefix ${BOTCRAFT_INSTALL_PATH}
)
