include(ExternalProject)

set(OPENSSL_GIT_REPOSITORY "https://github.com/janbar/openssl-cmake")
set(OPENSSL_GIT_BRANCH "master")

set(OPENSSL_SRC_PATH "${CMAKE_CURRENT_SOURCE_DIR}/dependency/openssl")
set(OPENSSL_BUILD_PATH "${CMAKE_CURRENT_BINARY_DIR}/dependency/openssl/build")
set(OPENSSL_INSTALL_PATH "${OPENSSL_BUILD_PATH}/install")
set(OPENSSL_HEADER_PATH "${OPENSSL_INSTALL_PATH}/include")
set(OPENSSL_LIB_PATH "${OPENSSL_INSTALL_PATH}/lib")
set(OPENSSL_BINARY_PATH "${OPENSSL_INSTALL_PATH}/bin")

if(NOT EXISTS "${OPENSSL_SRC_PATH}/.git")
  message(STATUS "Update submodule")
  execute_process(COMMAND ${GIT_EXECUTABLE} submodule update --init --recursive
                          WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
                          RESULT_VARIABLE GIT_SUBMOD_RESULT)
endif()

file(MAKE_DIRECTORY ${OPENSSL_BUILD_PATH})
file(MAKE_DIRECTORY ${OPENSSL_INSTALL_PATH})

ExternalProject_Add(Openssl
  SOURCE_DIR ${OPENSSL_SRC_PATH}
  STEP_TARGETS install
  EXCLUDE_FROM_ALL TRUE
  CMAKE_GENERATOR ${CMAKE_GENERATOR}
  CONFIGURE_COMMAND ${CMAKE_COMMAND} -S ${OPENSSL_SRC_PATH} -B ${OPENSSL_BUILD_PATH} -G ${CMAKE_GENERATOR} -DCMAKE_BUILD_TYPE=Release ${BUILD_PLATFORM} -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM} -DCMAKE_INSTALL_PREFIX=install -DWITH_APPS=OFF -DCPACK_SOURCE_7Z=OFF -DCPACK_SOURCE_ZIP=OFF -DMSVC_RUNTIME=dynamic -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  BUILD_COMMAND ${CMAKE_COMMAND} --build ${OPENSSL_BUILD_PATH} --config Release
  INSTALL_COMMAND ${CMAKE_COMMAND} --install ${OPENSSL_BUILD_PATH} --prefix ${OPENSSL_INSTALL_PATH}
)
