name: Build

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build:
    name: Build Project
    strategy:
      matrix:
        include:
          - os: windows-latest
            asset_name: MapArtist-windows-amd64
            generator: Visual Studio 17 2022
          - os: ubuntu-latest
            asset_name: MapArtist-linux-amd64
            generator: Unix Makefiles
          - os: macos-latest
            asset_name: MapArtist-macos-amd64
            generator: Unix Makefiles

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.2

      - name: Use CMake Action
        uses: threeal/cmake-action@main
        with:
          generator: ${{ matrix.generator }}
          build-args: --config Release
          run-build: true
      
      - name: Zip Binaries
        uses: vimtor/action-zip@v1.1
        with:
          files: bin
          dest: ${{ matrix.asset_name }}.zip

      - name: Check Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: ${{ github.workspace }}/${{ matrix.asset_name }}.zip
