name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: MapArtist-linux-amd64
          - os: windows-latest
            asset_name: MapArtist-windows-amd64

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          build-args: --config Release
          run-build: true
      
      - name: Zip Binaries
        uses: vimtor/action-zip@v1.1
        with:
          files: bin
          dest: ${{ matrix.asset_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: "executable-MSVC.zip"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ matrix.asset_name }}.zip