name: Build

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build Project (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.2

      - name: Use CMake Action
        uses: threeal/cmake-action@main
        with:
          generator: Visual Studio 17 2022
          build-args: --config Release
          run-build: true
      
      - name: Zip Binaries
        uses: vimtor/action-zip@v1.1
        with:
          files: bin
          dest: executable-Windows.zip

      - name: Check Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: ${{ github.workspace }}/executable-Windows.zip

  build-gcc:
    name: Build Project (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.2

      - name: Use CMake Action
        uses: threeal/cmake-action@main
        with:
          build-args: --config Release
          run-build: true
      
      - name: Zip Binaries
        uses: vimtor/action-zip@v1.1
        with:
          files: bin
          dest: executable-Linux.zip

      - name: Check Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: ${{ github.workspace }}/executable-Linux.zip