site_name: MapArtist
theme:
  language: en
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - ChangeLog: changelog.md

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh-TW
          name: 繁體中文
          build: true
          nav_translations:
            Home: MapArtist
            Install: 安裝
            Usage: 使用方法
            ChangeLog: 更新紀錄