site_name: MapArtist
site_url: !ENV [SITE_NAME, '']
repo_url: https://github.com/JueXiuHuang/MapArtist
theme:
  language: en
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate

nav:
  - MapArtist: index.md
  - Install: install.md
  - Usage: usage.md
  - Command: command.md
  - ChangeLog: changelog.md

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh-TW
          name: 繁體中文
          build: true
          link: /zh-TW/
          nav_translations:
            MapArtist: MapArtist
            Install: 安裝
            Usage: 使用方法
            Command: 指令
            ChangeLog: 更新紀錄