site_name: MapArtist
site_url: !ENV [SITE_NAME, '']
repo_url: https://github.com/JueXiuHuang/MapArtist
theme:
  language: en
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: custom
    GA_id: G-520S6QN15B
    umami_id: 2c76b2df-46bf-4df6-87cd-deb365059663
    umami_host: https://umami.bigcatblog.com/script.js

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Command: command.md
  - FAQ: faq.md
  # - ChangeLog: changelog.md

plugins:
  - site-urls
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh-TW
          name: 繁體中文
          build: true
          link: /zh-TW/
          nav_translations:
            Home: 首頁
            Install: 安裝
            Usage: 使用方法
            Command: 指令
            FAQ: 常見問題
            # ChangeLog: 更新紀錄